Repository IntegerAlex/hasty-server, pull requests merged in 2024-10, with the labels that each got.

#7 added basic doc for hasty server
  doc/.gitignore
  doc/README.md
  doc/eslint.config.js
  doc/index.html
  doc/package-lock.json
  doc/package.json
  doc/postcss.config.js
  doc/public/logo.png
  doc/src/components/features.jsx
  doc/src/components/general/typography.jsx
  doc/src/components/header.jsx
  doc/src/components/installation.jsx
  doc/src/components/introducation.jsx
  doc/src/components/quick-start.jsx
  doc/src/index.css
  doc/src/layout.jsx
  doc/src/lib/utils.jsx
  doc/src/main.jsx
  doc/tailwind.config.js
  doc/vite.config.js
Labels: documentation, enhancement, hacktoberfest

#17 fixed issue of .json sending Headers as body
  server/response.js
Labels: bug, hacktoberfest

#15 feature/http-req-res
  server/index.js
  server/response.js
  test/init.js
Labels: enhancement, hacktoberfest

#22 Custom License GOFL
  GPLV3.md
  LICENSE.md
  README.md
  package.json
Labels: documentation, hacktoberfest, License

#26 changed to dark theme
  doc/src/components/features.jsx
  doc/src/components/installation.jsx
  doc/src/components/introducation.jsx
  doc/src/components/quick-start.jsx
  doc/src/layout.jsx
Labels: documentation, enhancement, hacktoberfest

#28 Added HelloWorld and fixed Darcula to Dracula
  doc/src/components/helloWorld.jsx
  doc/src/components/installation.jsx
  doc/src/components/introducation.jsx
  doc/src/components/introduction.jsx
  doc/src/components/quick-start.jsx
  doc/src/layout.jsx
  doc/src/main.jsx
Labels: documentation, enhancement, hacktoberfest

#31 revamp
  .github/workflows/static.yml
  doc/package-lock.json
  doc/package.json
  doc/src/components/features.jsx
  doc/src/components/header.jsx
  doc/src/components/helloWorld.jsx
  doc/src/components/installation.jsx
  doc/src/components/introduction.jsx
  doc/src/components/quick-start.jsx
  doc/src/layout.jsx
  package-lock.json
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#38 Fixed #16
  lib/httpParser.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#39 fixing logo
  doc/index.html
  doc/src/components/header.jsx
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#23 Updated Contributing.md link in readme file
  README.md
Labels: question, hacktoberfest, hacktoberfest-accepted

#40 added a new NavBar list "view on github"
  doc/src/components/header.jsx
  package-lock.json
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#42 Need for Navigation buttons complete [fixed #33]
  doc/src/components/navigationButtons.jsx
  doc/src/index.css
  doc/src/main.jsx
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#45 Added MIME-type lookup and sendFile() method to response Object
  lib/mimeDb.js
  lib/utils.js
  server/index.js
  server/response.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#49 Fixed the issue Realated to formating HTTP1.1
  server/index.js
  server/response.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#62 Added Http error check
  server/index.js
  server/response.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#24 Create-Github-Action
  test-framework.yml
Labels: question

#64 Added tests for httpParser
  package.json
  test/httpParser.test.js
Labels: Test

#65 added Download method on response object
  server/response.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#70 Added support for cors headers
  server/index.js
  server/response.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#72 Added params #69
  CHANGELOG.md
  README.md
  package.json
  server/index.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#85 Updated license for Version 1
  GPLV3.md
  LICENSE.md
Labels: License
